### PR TITLE
Fixes towards making the cli functional with new event system

### PR DESCRIPTION
**Pull request by lunarrize**
Fix code so nari command will run and add fix for closing file when ActLogReader instance is GCd

### CODE REVIEW

**Review by ayyaruq — COMMENTED** [review]
Thanks for your contribution! Can you check the CI lint job failing? Looks pretty verbose and I'm not across pylint enough to tell if this is from the PR or just a newer version of pylint rules since the last time the job ran.

**Comment by lunarrize** [comment]
Whoever was working on this branch has a lot of code that doesn't lint??

nari/types/statuseffect.py:7:0: C0304: Final newline missing (missing-final-newline)
nari/types/statuseffect.py:1:0: C0114: Missing module docstring (missing-module-docstring)
nari/types/statuseffect.py:3:0: C0115: Missing class docstring (missing-class-docstring)
nari/types/statuseffect.py:1:0: W0611: Unused List imported from typing (unused-import)

Like this.. I didn't touch any of those files. I'll work on fixing them.

**Comment by lunarrize** [comment]
I cleaned up a lot, but there's still a lot in nari.types.. it even seems like there's duplicated events under event? I think because the branch is called event-rewrite the plan is to move those? I looked at the git history and that seems to be whats happening.. can I remove nari.types.event.act then?

**Comment by lunarrize** [comment]
@ayyaruq following up on this.. not sure if that module is safe to remove or not

**Comment by ayyaruq** [comment]
>I cleaned up a lot, but there's still a lot in nari.types.. it even seems like there's duplicated events under event? I think because the branch is called event-rewrite the plan is to move those? I looked at the git history and that seems to be whats happening.. can I remove nari.types.event.act then?
> @ayyaruq following up on this.. not sure if that module is safe to remove or not

As far as I recall that was the plan. If you're comfortable with doing it, please feel free!

**Comment by lunarrize** [comment]
@ayyaruq as discussed on discord, this PR should be ready to merge.

**Pull request merged**
